//
//  EABaseModel.h
//  EABluetooth
//
//  Created by Aye on 2021/3/18.
//  File Name:Base Model【模型基类】

#import <Foundation/Foundation.h>
#import <EABluetooth/EAEnum.h>
#import <YYKit/YYKit.h>
#import <EABluetooth/EADataValue.h>
#import <EABluetooth/EAModelCustomPropertyMapperConfig.h>
#import <EABluetooth/EADataInfoModel.h>

@class GPBMessage;
@class EABaseModel;
@class EARespondModel;
NS_ASSUME_NONNULL_BEGIN

typedef void(^ResultGetInfoBlock)(EABaseModel *baseModel);
typedef void(^RespondBlock)(EARespondModel *respondModel);
typedef void(^ResultGetPpgBlock)(NSString *ppgData);

/**
 * EABaseModel is the parent class of all data objects, with watch command methods such as getting and setting.
 * EABaseModel是所有数据对象的父类，有获取、设置等手表命令方法。
 */
@interface EABaseModel : NSObject<NSCopying>


/// Modify the data【修改数据】
/// - Parameter completion: completion
- (void)eaSend:(void (^)(EARespondCodeType respondCodeType ))completion;

/// Obtain data【获取数据】
/// - Parameter result: result
+ (void)eaGet:(ResultGetInfoBlock )result;


/// Obtain data【获取数据】
/// - Parameters:
///   - dataInfoType: data info type
///   - result: result
+ (void)eaGetWithType:(EADataInfoType)dataInfoType result:(ResultGetInfoBlock )result;











/// NOT_ANALYSIS_FUNCTION
/// General conversion method【通用转换方法】
/// - Parameters:
/// - data: Bluetooth data stream【蓝牙数据流】
/// - aClass: Data stream type【数据流类型】
+ (instancetype)getClassValueByData:(NSData *)data fromClass:(Class )aClass;



/// NOT_ANALYSIS_FUNCTION
/// Obtain the data stream【获取数据流】
/// - Parameter aClass: Data stream type【数据流类型】
- (NSData *)getModelDataByClass:(Class )aClass;


/// NOT_ANALYSIS_FUNCTION
/// Obtain the current data stream type data stream【获取当前数据流类型数据流】
- (NSData *)getModelData;

/// NOT_ANALYSIS_FUNCTION
/// 获取数据类型 -- 子类必须要重写此方法
- (EADataInfoModel *)getDataInfoModel;

/// NOT_ANALYSIS_FUNCTION
+ (instancetype )getModelByData:(NSData *)data;




@end

/**
 * EABigDataModel is the parent class of all big data types and contains the timestamps generated by big data.
 * EABigDataModel是所有大数据类型的父类，含有大数据产生的时间戳.
 */
@interface EABigDataModel : EABaseModel

/// The time stamp
/// 时间戳
@property(nonatomic, assign) NSInteger timeStamp;

@end

NS_ASSUME_NONNULL_END
